### ISSUE TITLE
keyError: 'schema'

### ISSUE THREAD

**Issue by rodrigolearns** [kuleuven/mango-portal#3]
Dear mango community,

Happy to make my first issue for the development of this very nice interface.
We have set up a containerized instance of iRODS and deployed mango as an interface for testing at AmsterdamUMC.
The installation is quite smooth, however we ran into an issue when trying to apply metadata schemas:
There are no options in the drop-down menu of "Edit/add metadata via schema"
I added the podman logs below:

`ERROR:app:'schema'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/kernel/metadata_schema/form.py", line 144, in edit_schema_metadata_for_item
    template_name = schema = _parameters["schema"]
KeyError: 'schema'`

Bests,
Rodrigo

**Comment by MirjamSchr** [comment]
This is very similar, if not the same as #4.
